# Generated by Django 2.2.6 on 2019-10-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20191010_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('height_inches', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('using', models.BooleanField(choices=[[True, 'Ski'], [False, 'Snowboard']], default=True)),
                ('stance', models.BooleanField(blank=True, choices=[[True, 'Regular'], [False, 'Goofy']], default=True)),
                ('ski_type', models.IntegerField(choices=[[1, 'Type 1'], [2, 'Type 2'], [3, 'Type 3']], default=1)),
                ('input_date', models.DateField(auto_now_add=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.renter')),
            ],
        ),
    ]
