# Generated by Django 2.2.6 on 2019-10-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ski_type',
            field=models.IntegerField(blank=True, choices=[[0, 'None'], [1, 'Type 1'], [2, 'Type 2'], [3, 'Type 3']], default=1),
        ),
        migrations.AlterField(
            model_name='rental',
            name='stance',
            field=models.BooleanField(blank=True, choices=[['', 'None'], [True, 'Regular'], [False, 'Goofy']], default=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='using',
            field=models.BooleanField(blank=True, choices=[[True, 'Ski'], [False, 'Snowboard']], default=True),
        ),
    ]
