# Generated by Django 2.2.6 on 2019-10-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20191019_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='stance',
            field=models.BooleanField(blank=True, choices=[[None, 'None'], [True, 'Regular'], [False, 'Goofy']], default=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='using',
            field=models.IntegerField(blank=True, choices=[[True, 'Ski'], [False, 'Snowboard']], default=True),
        ),
    ]
