# Generated by Django 2.2.6 on 2019-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_auto_20191022_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ski_type',
            field=models.IntegerField(choices=[[0, 'None'], [1, 'Type 1'], [2, 'Type 2'], [3, 'Type 3']], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='stance',
            field=models.IntegerField(blank=True, choices=[[-1, 'None'], [True, 'Regular'], [False, 'Goofy']], default=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='using',
            field=models.BooleanField(choices=[[True, 'Ski'], [False, 'Snowboard']], default=True),
        ),
    ]
