# Generated by Django 2.2.6 on 2019-11-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_20191029_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='input_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
