# Generated by Django 2.2.6 on 2019-11-19 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_auto_20191119_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 20, 29, 25, 216073)),
        ),
    ]
