# Generated by Django 2.2.6 on 2019-11-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20191119_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='input_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
