# Generated by Django 2.2.6 on 2019-10-09 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191006_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 9, 17, 51, 43, 635697)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2019, 10, 9, 17, 51, 43, 635697)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
