# Generated by Django 2.2.6 on 2019-10-10 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191010_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 22, 21, 48, 170318)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 22, 21, 48, 170318)),
        ),
    ]
