# Generated by Django 2.2.6 on 2019-10-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191013_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'User Info'},
        ),
    ]
