# Generated by Django 2.2.6 on 2019-11-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191019_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userInfo',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.UserInfo'),
            preserve_default=False,
        ),
    ]
