# Generated by Django 2.2.6 on 2019-11-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userInfo',
            new_name='UserInfo',
        ),
    ]
